# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160518_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='手机号'),
        ),
    ]
