# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160518_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xuehao',
            field=models.CharField(default='', max_length=20, verbose_name='学号'),
        ),
    ]
