# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160518_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='huiyuan',
            field=models.IntegerField(default=0, verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(default='', max_length=10, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '老师')], default='', max_length=10, verbose_name='身份'),
        ),
    ]
