# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160518_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yuanxi',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=10, verbose_name='身份'),
        ),
    ]
