# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='品牌名称')),
                ('index', models.IntegerField(default=1, verbose_name='排列顺序')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=50, verbose_name='Token')),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名')),
                ('desc', models.CharField(default='', max_length=100, verbose_name='商品简介')),
                ('detail', models.TextField(default='', verbose_name='商品详情')),
                ('color', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='颜色')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('number', models.IntegerField(default=0, verbose_name='库存')),
                ('img_show', models.ImageField(default='product/default.jpg', upload_to='product/show/', verbose_name='展示图片地址')),
                ('img_detail_1', models.ImageField(default='product/default.jpg', upload_to='product/detail/', verbose_name='详情图片地址')),
                ('img_detail_2', models.ImageField(default='product/default.jpg', upload_to='product/detail/', verbose_name='详情图片地址')),
                ('img_detail_3', models.ImageField(default='product/default.jpg', upload_to='product/detail/', verbose_name='详情图片地址')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shangcheng.Brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='产品分类名')),
                ('index', models.IntegerField(default=1, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shangcheng.ProductCategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='商品版本')),
                ('old_prize', models.FloatField(default=0.0, verbose_name='原价')),
                ('discount', models.FloatField(default=1, verbose_name='折扣')),
                ('now_prize', models.FloatField(default=0, verbose_name='现价')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangcheng.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品版本',
                'verbose_name_plural': '商品版本',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shangcheng.ProductCategory', verbose_name='产品分类'),
        ),
    ]
