# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangcheng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='0', max_length=5, verbose_name='状态'),
        ),
    ]
