# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangcheng', '0003_auto_20160520_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='shangcheng.Product', verbose_name='商品'),
        ),
    ]
