# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangcheng', '0005_auto_20160520_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='token',
        ),
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.CharField(default='', max_length=80, verbose_name='Token'),
        ),
    ]
