# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangcheng', '0007_auto_20160520_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tuijian',
            field=models.BooleanField(default=False, verbose_name='是否首页推荐'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', '上线'), ('0', '采购中')], default='', max_length=5, verbose_name='状态'),
        ),
    ]
