# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import shangcheng.models


class Migration(migrations.Migration):

    dependencies = [
        ('shangcheng', '0008_auto_20160520_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_detail_1',
            field=models.ImageField(blank=True, null=True, upload_to='product/detail/', verbose_name='详情图片地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_detail_2',
            field=models.ImageField(blank=True, null=True, upload_to='product/detail/', verbose_name='详情图片地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_detail_3',
            field=models.ImageField(blank=True, null=True, upload_to='product/detail/', verbose_name='详情图片地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_show',
            field=models.ImageField(blank=True, null=True, upload_to=shangcheng.models.PathAndRename('product/show/'), verbose_name='展示图片地址'),
        ),
    ]
