# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangcheng', '0012_auto_20160520_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='', max_length=10, verbose_name='单位'),
        ),
    ]
