# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangcheng', '0014_auto_20160604_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='', max_length=80, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', '采购中'), ('1', '上线')], default='', max_length=5, verbose_name='状态'),
        ),
    ]
